version: "3.9"

services:
  mysql-server:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=persons
      - MYSQL_USER=plop
      - MYSQL_PASSWORD=plop
    ports:
      - 3306:3306
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql

  spring-boot-native-image:
    image: org.craftedsw.kirin.poc-spring-boot-native-image:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server




